remote_theme: tuur29/pages-themes-cayman
title: Movie Time
markdown: kramdown

darkmode: true
hide_first_title: true
show_downloads: true
buttons:
  zip_url: tacospin.com
  zip_title: zip Title
  zip_hide: false
  tar_hide: true
