remote_theme: tuur29/pages-themes-cayman
title: Movie Time
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
  
darkmode: true
hide_first_title: true
logo_url: https://imgur.com/XUqSIS4.png
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

show_downloads: true
buttons:
  zip_url: https://github.com/tal-sitton/Movie-Time/releases/download/v1.0.1/movie-time.apk
  zip_title: Download The App
  zip_hide: true
  tar_title: Download The App
  tar_url: https://play.google.com/store/apps/details?id=com.talsitton.movietime
  tar_hide: false
