name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.2.0
      with:
        project-path: .
        output-path: movie-time.apk
        browserstack-upload: false
        
    - name: save artifacts  
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: movie-time.apk

