name: Android CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.3.4
      with:
        project-path: .
        output-path: movie-time.apk
        browserstack-upload: false
        ruby-version: "2.7.5"
        bundler-version: "2.3.26"
        fastlane-env: "debug"
        
    - name: save artifacts  
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: movie-time.apk

