name: Android CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.4.0
      with:
        project-path: .
        output-path: movie-time.apk
        browserstack-upload: false
        ruby-version: "3.2.2"
        bundler-version: "2.4.13"
        fastlane-env: "debug"
        
    - name: save artifacts  
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: movie-time.apk

